-- AI Trademark & Brand Protection Monitor - Seed Data
-- Truncate all tables before inserting

TRUNCATE TABLE audit_logs, alerts, reports, legal_cases, marketplace_listings, logo_analyses, competitors, sentiment_analyses, trademark_searches, cease_desist_letters, counterfeits, social_mentions, domains, infringements, trademarks, users RESTART IDENTITY CASCADE;

-- ===================== USERS =====================
INSERT INTO users (email, password, name, role) VALUES
('demo@trademark.com', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Demo User', 'admin'),
('sarah.chen@trademark.com', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Sarah Chen', 'admin'),
('james.wilson@trademark.com', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'James Wilson', 'user'),
('maria.garcia@trademark.com', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Maria Garcia', 'user'),
('david.kim@trademark.com', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'David Kim', 'analyst'),
('emma.thompson@trademark.com', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Emma Thompson', 'analyst'),
('robert.jones@trademark.com', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Robert Jones', 'user'),
('lisa.wang@trademark.com', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Lisa Wang', 'user'),
('michael.brown@trademark.com', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Michael Brown', 'admin'),
('jennifer.lee@trademark.com', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Jennifer Lee', 'analyst'),
('alex.martinez@trademark.com', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Alex Martinez', 'user'),
('rachel.taylor@trademark.com', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Rachel Taylor', 'user'),
('kevin.patel@trademark.com', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Kevin Patel', 'analyst'),
('amanda.white@trademark.com', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Amanda White', 'user'),
('chris.johnson@trademark.com', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Chris Johnson', 'user');

-- ===================== TRADEMARKS =====================
INSERT INTO trademarks (name, registration_number, status, jurisdiction, filing_date, expiry_date, class, owner, description) VALUES
('NovaTech', 'US-TM-2024-001234', 'active', 'United States', '2022-03-15', '2032-03-15', 'Class 9 - Software', 'NovaTech Industries Inc.', 'Software platform for enterprise data analytics and AI solutions'),
('AquaPure', 'US-TM-2023-005678', 'active', 'United States', '2021-07-22', '2031-07-22', 'Class 32 - Beverages', 'AquaPure Beverages LLC', 'Premium purified water and health beverages'),
('SwiftLogix', 'EU-TM-2024-009012', 'active', 'European Union', '2023-01-10', '2033-01-10', 'Class 42 - Technology', 'SwiftLogix GmbH', 'Cloud logistics and supply chain management platform'),
('GreenLeaf Organics', 'US-TM-2022-003456', 'active', 'United States', '2020-11-05', '2030-11-05', 'Class 29 - Food Products', 'GreenLeaf Organics Corp.', 'Organic and sustainable food products'),
('VeloCity Bikes', 'US-TM-2023-007890', 'active', 'United States', '2022-06-18', '2032-06-18', 'Class 12 - Vehicles', 'VeloCity Cycling Inc.', 'Premium electric bicycles and cycling accessories'),
('LuxeVault', 'UK-TM-2024-002345', 'active', 'United Kingdom', '2023-04-30', '2033-04-30', 'Class 14 - Jewelry', 'LuxeVault Holdings Ltd.', 'Luxury jewelry and timepiece storage solutions'),
('MediCare Plus', 'US-TM-2023-006789', 'active', 'United States', '2021-09-12', '2031-09-12', 'Class 44 - Medical', 'MediCare Plus Health Systems', 'Telemedicine platform and digital health services'),
('SoundWave Audio', 'US-TM-2024-000123', 'active', 'United States', '2023-02-28', '2033-02-28', 'Class 9 - Electronics', 'SoundWave Audio Corp.', 'Premium headphones, speakers, and audio equipment'),
('TerraFirm Construction', 'US-TM-2022-004567', 'active', 'United States', '2020-08-14', '2030-08-14', 'Class 37 - Construction', 'TerraFirm Construction Group', 'Commercial and residential construction services'),
('PixelForge', 'EU-TM-2023-008901', 'active', 'European Union', '2022-12-01', '2032-12-01', 'Class 42 - Design', 'PixelForge Creative Studio', 'Digital design tools and creative software suite'),
('FrostByte Gaming', 'US-TM-2024-002345', 'active', 'United States', '2023-05-20', '2033-05-20', 'Class 41 - Entertainment', 'FrostByte Entertainment Inc.', 'Video game development and esports platform'),
('AeroVista', 'US-TM-2023-006789', 'active', 'United States', '2022-10-08', '2032-10-08', 'Class 12 - Aerospace', 'AeroVista Technologies', 'Drone technology and aerial imaging services'),
('Botanica Wellness', 'CA-TM-2024-001234', 'active', 'Canada', '2023-03-25', '2033-03-25', 'Class 3 - Cosmetics', 'Botanica Wellness Ltd.', 'Natural skincare and wellness products'),
('CodeNexus', 'US-TM-2024-005678', 'active', 'United States', '2023-08-15', '2033-08-15', 'Class 42 - Technology', 'CodeNexus Software Inc.', 'Developer tools and code collaboration platform'),
('PeakPerformance Athletics', 'US-TM-2022-009012', 'active', 'United States', '2021-04-10', '2031-04-10', 'Class 25 - Apparel', 'PeakPerformance Athletics Corp.', 'Athletic apparel and performance sportswear'),
('SolarFlare Energy', 'US-TM-2023-003456', 'pending', 'United States', '2023-11-30', '2033-11-30', 'Class 11 - Energy', 'SolarFlare Energy Solutions', 'Solar panel systems and renewable energy solutions');

-- ===================== INFRINGEMENTS =====================
INSERT INTO infringements (trademark_id, source_url, infringement_type, severity, status, description, ai_analysis, detected_at) VALUES
(1, 'https://novatek-solutions.com', 'domain_squatting', 'high', 'pending', 'Similar domain registered with slight spelling variation targeting NovaTech brand', 'High risk: Domain novatek-solutions.com has 92% similarity to NovaTech trademark. The site appears to sell competing software products. Immediate action recommended.', '2025-12-01 10:30:00'),
(2, 'https://amazon.com/dp/B09FAKE1234', 'counterfeit_product', 'critical', 'investigating', 'Counterfeit AquaPure water bottles sold on Amazon with replicated branding', 'Critical: Product listing uses identical AquaPure logo and branding. Seller has no authorized relationship. 47 units sold in last 30 days.', '2025-11-28 14:15:00'),
(3, 'https://swiftlogics.io', 'domain_squatting', 'medium', 'pending', 'Domain swiftlogics.io registered, similar to SwiftLogix', 'Medium risk: Domain differs by one character. Currently shows a parked page with ads. Monitor for future development.', '2025-12-05 09:00:00'),
(4, 'https://ebay.com/itm/fake-greenleaf', 'counterfeit_product', 'high', 'resolved', 'Unauthorized use of GreenLeaf Organics branding on eBay food products', 'High risk: Seller using GreenLeaf brand name and similar packaging. Product quality cannot be verified. Listing removed after report.', '2025-10-15 16:45:00'),
(5, 'https://aliexpress.com/item/velocity-ebike', 'counterfeit_product', 'critical', 'pending', 'Counterfeit VeloCity electric bikes sold on AliExpress at fraction of original price', 'Critical: Multiple sellers offering VeloCity-branded e-bikes at $299 (original $2,499). Safety concern due to battery quality.', '2025-12-08 11:20:00'),
(6, 'https://luxevaultt.com', 'domain_squatting', 'high', 'investigating', 'Typosquatting domain luxevaultt.com with extra T', 'High risk: Domain serves a phishing page mimicking LuxeVault. Collecting customer payment information. Urgent takedown needed.', '2025-12-03 08:30:00'),
(7, 'https://medicare-plus-discount.com', 'trademark_misuse', 'high', 'pending', 'Unauthorized use of MediCare Plus name in discount pharmacy scheme', 'High risk: Website uses MediCare Plus name to sell unauthorized prescription medications. Patient safety concern.', '2025-11-20 13:00:00'),
(8, 'https://tiktok.com/@fakesoundwave', 'social_media', 'medium', 'investigating', 'TikTok account using SoundWave branding to promote knockoff products', 'Medium risk: Account has 45K followers. Promotes counterfeit headphones using SoundWave brand imagery. 230+ videos posted.', '2025-12-10 15:30:00'),
(9, 'https://terrafirm-builders.com', 'domain_squatting', 'low', 'resolved', 'Similar domain registered in different construction market', 'Low risk: Domain registered by legitimate construction company in different region. No direct competition or consumer confusion.', '2025-09-22 10:00:00'),
(10, 'https://pixelforge-free.com', 'trademark_misuse', 'high', 'pending', 'Website offering pirated PixelForge software downloads', 'High risk: Site distributes cracked versions of PixelForge software. 15,000+ downloads estimated. Contains malware.', '2025-12-07 07:45:00'),
(11, 'https://frost-byte-games.com', 'domain_squatting', 'medium', 'pending', 'Domain registered with hyphenated version of FrostByte Gaming', 'Medium risk: Domain redirects to a competing game store. May cause brand confusion among gamers.', '2025-11-30 12:15:00'),
(12, 'https://instagram.com/aerovista_drones', 'social_media', 'low', 'resolved', 'Instagram account using AeroVista name for drone photography services', 'Low risk: Small local business using similar name. No direct trademark conflict in current markets. Monitor recommended.', '2025-10-05 09:30:00'),
(13, 'https://botanica-beauty.com', 'trademark_misuse', 'medium', 'investigating', 'Website selling skincare under Botanica name with similar branding', 'Medium risk: Competing skincare brand using Botanica name with leaf imagery. May cause consumer confusion in cosmetics market.', '2025-12-02 14:00:00'),
(14, 'https://codenexus-pro.com', 'domain_squatting', 'high', 'pending', 'Domain offering fake CodeNexus subscriptions', 'High risk: Phishing site collecting developer credentials. Mimics CodeNexus login page. 500+ potential victims identified.', '2025-12-09 16:00:00'),
(15, 'https://peakperformance-outlet.com', 'counterfeit_product', 'critical', 'investigating', 'Fake outlet store selling counterfeit PeakPerformance athletic wear', 'Critical: Professional-looking fake outlet site. Uses stolen product images. Credit card fraud risk for customers.', '2025-12-06 11:00:00');

-- ===================== DOMAINS =====================
INSERT INTO domains (domain_name, similarity_score, registrar, registration_date, status, threat_level, related_trademark, ai_analysis) VALUES
('novatek-solutions.com', 92.50, 'Namecheap Inc.', '2025-06-15', 'active', 'high', 'NovaTech', 'Domain has 92.5% similarity to NovaTech. Registered anonymously via privacy proxy. Hosts competing software product.'),
('aqua-pure-water.com', 85.30, 'GoDaddy LLC', '2025-03-22', 'active', 'medium', 'AquaPure', 'Hyphenated version of AquaPure brand name. Currently a parked page with beverage-related ads.'),
('swiftlogics.io', 88.70, 'Cloudflare Inc.', '2025-08-10', 'active', 'medium', 'SwiftLogix', 'One character difference from SwiftLogix. Parked domain with tech ads.'),
('luxevaultt.com', 95.00, 'NameSilo LLC', '2025-09-01', 'active', 'critical', 'LuxeVault', 'Typosquatting with double T. Active phishing site mimicking LuxeVault storefront.'),
('greenleaf-organic.com', 90.20, 'Namecheap Inc.', '2025-01-18', 'active', 'high', 'GreenLeaf Organics', 'Missing plural form. Sells competing organic products with similar branding.'),
('vellocity-bikes.com', 87.40, 'GoDaddy LLC', '2025-04-30', 'active', 'medium', 'VeloCity Bikes', 'Double L typosquat. Currently redirects to AliExpress bike listings.'),
('medicare-plus-rx.com', 91.80, 'Tucows Inc.', '2025-07-12', 'active', 'critical', 'MediCare Plus', 'Unauthorized pharmacy site using MediCare Plus brand name.'),
('soundwave-audio.shop', 82.60, 'Shopify Inc.', '2025-05-25', 'active', 'medium', 'SoundWave Audio', 'Shopify store selling knockoff audio products under similar name.'),
('pixelforge.io', 96.00, 'Cloudflare Inc.', '2024-11-08', 'active', 'high', 'PixelForge', 'Exact brand name on different TLD. Distributes pirated software.'),
('frostbyte-gaming.com', 89.50, 'Namecheap Inc.', '2025-02-14', 'active', 'medium', 'FrostByte Gaming', 'Hyphenated variant. Hosts unauthorized game key reselling.'),
('aero-vista.com', 84.10, 'GoDaddy LLC', '2025-10-20', 'active', 'low', 'AeroVista', 'Hyphenated version. Small drone service operator website.'),
('botanicawellness.co', 93.20, 'Namecheap Inc.', '2025-08-05', 'active', 'high', 'Botanica Wellness', 'Nearly identical name on .co TLD. Sells competing skincare products.'),
('codenexus-pro.com', 88.90, 'NameSilo LLC', '2025-09-18', 'active', 'critical', 'CodeNexus', 'Phishing site targeting CodeNexus users for credential harvesting.'),
('peakperformance-outlet.com', 91.30, 'GoDaddy LLC', '2025-06-30', 'active', 'critical', 'PeakPerformance Athletics', 'Fake outlet store. Professional design selling counterfeit goods.'),
('terrafirm-builders.net', 80.50, 'Tucows Inc.', '2024-08-22', 'inactive', 'low', 'TerraFirm Construction', 'Legitimate construction company. No direct IP conflict.'),
('solarflare-panels.com', 86.70, 'Namecheap Inc.', '2025-11-01', 'active', 'medium', 'SolarFlare Energy', 'Similar domain selling competing solar products. Uses comparable branding.');

-- ===================== SOCIAL MENTIONS =====================
INSERT INTO social_mentions (platform, author, content, url, sentiment, reach, engagement, trademark_mentioned, detected_at) VALUES
('Twitter', '@TechReviewDaily', 'Just tested the new NovaTech analytics platform. Impressive AI capabilities! #NovaTech #DataAnalytics', 'https://twitter.com/TechReviewDaily/status/123456', 'positive', 45000, 1230, 'NovaTech', '2025-12-10 09:15:00'),
('Instagram', '@HealthyLiving_Blog', 'Love my daily AquaPure water delivery! Best tasting purified water on the market 💧', 'https://instagram.com/p/AquaPure123', 'positive', 28000, 3450, 'AquaPure', '2025-12-09 14:30:00'),
('Reddit', 'u/supplychain_pro', 'SwiftLogix just released their new warehouse integration. Game changer for mid-size businesses.', 'https://reddit.com/r/logistics/comments/swiftlogix', 'positive', 15000, 892, 'SwiftLogix', '2025-12-08 11:00:00'),
('Twitter', '@FakeAlert2024', 'WARNING: Fake GreenLeaf Organics products found at local market. Check packaging carefully!', 'https://twitter.com/FakeAlert2024/status/789012', 'negative', 62000, 4500, 'GreenLeaf Organics', '2025-12-07 16:45:00'),
('YouTube', 'ElectricBikeReviews', 'VeloCity E-Bike Review - Is it worth $2,499? Full test after 6 months of daily use', 'https://youtube.com/watch?v=VeloCity2024', 'positive', 120000, 8900, 'VeloCity Bikes', '2025-12-06 10:00:00'),
('TikTok', '@LuxuryUnboxing', 'Unboxing my new LuxeVault jewelry box - the craftsmanship is unreal! #LuxeVault #Luxury', 'https://tiktok.com/@LuxuryUnboxing/video/12345', 'positive', 89000, 12300, 'LuxeVault', '2025-12-05 19:30:00'),
('Twitter', '@HealthTechNews', 'MediCare Plus telemedicine platform experiences outage during peak hours. Users frustrated.', 'https://twitter.com/HealthTechNews/status/345678', 'negative', 38000, 2100, 'MediCare Plus', '2025-12-04 08:00:00'),
('Reddit', 'u/audiophile_daily', 'SoundWave headphones vs Sony WH-1000XM5. Honest comparison after 3 months. SoundWave surprised me.', 'https://reddit.com/r/headphones/comments/soundwave', 'positive', 22000, 1560, 'SoundWave Audio', '2025-12-03 13:15:00'),
('Facebook', 'PixelForge Community', 'New PixelForge 4.0 update is buggy. Lost 2 hours of work due to autosave failure.', 'https://facebook.com/groups/pixelforge/post/987654', 'negative', 8500, 670, 'PixelForge', '2025-12-02 15:45:00'),
('Twitter', '@GamerWeekly', 'FrostByte Gaming announces new RPG title. Pre-orders already breaking records! #FrostByteGaming', 'https://twitter.com/GamerWeekly/status/567890', 'positive', 95000, 7800, 'FrostByte Gaming', '2025-12-01 12:00:00'),
('Instagram', '@DronePhotography', 'Captured stunning aerial shots with AeroVista drones. The stabilization tech is next level 📸', 'https://instagram.com/p/AeroVista456', 'positive', 34000, 4200, 'AeroVista', '2025-11-30 17:30:00'),
('TikTok', '@SkincareExpert', 'Botanica Wellness face serum review - 30 day results. My skin has never looked better!', 'https://tiktok.com/@SkincareExpert/video/67890', 'positive', 156000, 18500, 'Botanica Wellness', '2025-11-29 20:00:00'),
('Twitter', '@DevTools_Review', 'CodeNexus just shipped real-time collaboration. Finally a worthy GitHub alternative for teams.', 'https://twitter.com/DevTools_Review/status/901234', 'positive', 52000, 3400, 'CodeNexus', '2025-11-28 10:30:00'),
('Reddit', 'u/fitness_gear_reviews', 'PeakPerformance running tights review - premium quality but overpriced for what you get.', 'https://reddit.com/r/running/comments/peakperf', 'neutral', 11000, 890, 'PeakPerformance Athletics', '2025-11-27 14:00:00'),
('Twitter', '@CounterfeitWatch', 'ALERT: Fake SoundWave headphones flooding Amazon marketplace. Check serial numbers!', 'https://twitter.com/CounterfeitWatch/status/112233', 'negative', 73000, 5600, 'SoundWave Audio', '2025-11-26 09:45:00'),
('LinkedIn', 'SolarFlare Energy CEO', 'Excited to announce SolarFlare Energy Series B funding of $45M. Scaling renewable solutions nationwide.', 'https://linkedin.com/posts/solarflare-funding', 'positive', 18000, 2300, 'SolarFlare Energy', '2025-11-25 11:00:00');

-- ===================== COUNTERFEITS =====================
INSERT INTO counterfeits (product_name, platform, seller, url, price, original_price, status, evidence, ai_analysis, detected_at) VALUES
('NovaTech Enterprise License (Pirated)', 'Dark Web Forums', 'CrackKing_2024', 'https://darkweb-market.onion/novatech-crack', 29.99, 4999.00, 'active', 'Cracked software with embedded malware. Distributed via torrent and direct download.', 'Critical: Pirated NovaTech software contains trojan horse. 2,300+ downloads estimated. Revenue loss approximately $11.5M.', '2025-12-08 10:00:00'),
('AquaPure Water Bottles (Fake)', 'Amazon', 'BestWaterDeals', 'https://amazon.com/dp/B09FAKE5678', 8.99, 24.99, 'investigating', 'Counterfeit bottles with replicated labels. Water quality untested.', 'High risk: Packaging nearly identical. Water source unknown. Potential health hazard. 890 units sold.', '2025-12-05 14:30:00'),
('VeloCity E-Bike (Knockoff)', 'AliExpress', 'ShenZhen_eBikes', 'https://aliexpress.com/item/velocity-clone', 299.00, 2499.00, 'active', 'Counterfeit e-bike with VeloCity branding. Unsafe battery components.', 'Critical: Counterfeit e-bikes with substandard lithium batteries. Fire hazard. 156 units shipped worldwide.', '2025-12-07 09:15:00'),
('LuxeVault Jewelry Box (Replica)', 'DHGate', 'LuxuryReplicas_HK', 'https://dhgate.com/product/luxevault-replica', 45.00, 899.00, 'active', 'High-quality replica using similar materials and branding.', 'High risk: Replica closely matches original design. Uses LuxeVault logo. 340 units sold in 60 days.', '2025-12-06 11:45:00'),
('SoundWave Pro Headphones (Fake)', 'Amazon', 'AudioDeals_Store', 'https://amazon.com/dp/B09FAKE9012', 39.99, 349.99, 'investigating', 'Counterfeit headphones with copied design. Poor audio quality and no noise cancellation.', 'Critical: Near-identical packaging. No active noise cancellation despite claims. 2,100+ units sold with 1-star reviews.', '2025-12-04 16:00:00'),
('PixelForge Pro License (Cracked)', 'Pirate Sites', 'CrackZone', 'https://crack-zone.to/pixelforge-pro', 0.00, 599.00, 'active', 'Cracked software with keylogger embedded.', 'Critical: Malware-laden pirated software. Keylogger captures user credentials. 8,500+ installations detected.', '2025-12-03 08:30:00'),
('FrostByte Gaming Controller (Clone)', 'Wish', 'GamerGear_CN', 'https://wish.com/product/frostbyte-controller', 12.99, 79.99, 'active', 'Cheap clone with FrostByte branding. Stick drift issues within days.', 'Medium risk: Low-quality controller using FrostByte name. 5,600 units sold. Multiple consumer complaints.', '2025-12-02 13:00:00'),
('GreenLeaf Organic Snacks (Fake)', 'eBay', 'OrganicBargains', 'https://ebay.com/itm/greenleaf-organic-bars', 15.99, 32.99, 'resolved', 'Non-organic products in counterfeit GreenLeaf packaging.', 'High risk: Products not certified organic despite labeling. False health claims. Listing removed.', '2025-11-28 10:20:00'),
('Botanica Wellness Serum (Counterfeit)', 'Instagram Shop', '@botanica_deals', 'https://instagram.com/shop/botanica_deals', 19.99, 89.99, 'active', 'Counterfeit serum with unknown ingredients.', 'Critical: Unknown chemical composition. Potential skin reaction risk. Sold via Instagram ads targeting Botanica audience.', '2025-12-01 15:30:00'),
('PeakPerformance Running Shoes (Fake)', 'StockX', 'SneakerKing99', 'https://stockx.com/peak-performance-fake', 89.99, 189.99, 'investigating', 'Counterfeit running shoes with inferior sole material.', 'High risk: Sole material degrades quickly. May cause foot injuries during running. 780 pairs sold.', '2025-11-30 12:00:00'),
('CodeNexus Team License (Pirated)', 'Telegram', 'SoftwareDeals_Bot', 'https://t.me/software_deals/codenexus', 19.99, 299.00, 'active', 'Stolen license keys distributed via Telegram bot.', 'High risk: License keys harvested from compromised accounts. 450+ keys distributed.', '2025-12-09 07:00:00'),
('MediCare Plus App (Clone)', 'APK Sites', 'APK_Mirror_Fake', 'https://fake-apk-site.com/medicare-plus', 0.00, 0.00, 'active', 'Cloned app harvesting patient medical data.', 'Critical: Fake app collects sensitive health information. HIPAA violation risk. 3,200+ installs.', '2025-11-25 09:45:00'),
('AeroVista Drone (Knockoff)', 'Banggood', 'DroneFactory_SZ', 'https://banggood.com/AeroVista-Clone', 149.99, 1299.00, 'active', 'Cheap drone clone with AeroVista branding. No flight stabilization.', 'High risk: Drone lacks safety features. GPS malfunctions reported. 290 units sold.', '2025-11-27 14:15:00'),
('TerraFirm Hard Hat (Counterfeit)', 'Amazon', 'SafetyGear_Direct', 'https://amazon.com/dp/B09FAKE3456', 12.99, 49.99, 'investigating', 'Counterfeit safety equipment with TerraFirm logo.', 'Critical: Safety equipment not meeting OSHA standards. Worker injury risk. 1,200 units in circulation.', '2025-12-04 10:30:00'),
('SolarFlare Solar Panels (Fake)', 'Alibaba', 'SolarPanel_Mfg', 'https://alibaba.com/product/solarflare-panels', 199.00, 899.00, 'active', 'Counterfeit solar panels with SolarFlare branding. Substandard cells.', 'High risk: Panels produce 40% less energy than claimed. Fire risk from poor wiring. 85 units shipped.', '2025-12-08 16:45:00');

-- ===================== CEASE & DESIST LETTERS =====================
INSERT INTO cease_desist_letters (recipient_name, recipient_email, trademark, infringement_type, status, letter_content, ai_generated) VALUES
('John Smith (novatek-solutions.com)', 'admin@novatek-solutions.com', 'NovaTech', 'domain_squatting', 'sent', 'Dear John Smith, This letter serves as formal notice that your domain novatek-solutions.com infringes upon the registered trademark NovaTech (US-TM-2024-001234). We demand immediate transfer or deactivation of this domain within 15 business days...', true),
('BestWaterDeals (Amazon Seller)', 'contact@bestwaterdeals.com', 'AquaPure', 'counterfeit_product', 'draft', 'Dear BestWaterDeals, We have identified your Amazon listings as containing counterfeit AquaPure branded products. This constitutes trademark infringement under the Lanham Act...', true),
('ShenZhen_eBikes (AliExpress)', 'shenzhen.ebikes@alibaba.com', 'VeloCity Bikes', 'counterfeit_product', 'sent', 'To Whom It May Concern, Your AliExpress store is selling unauthorized products bearing the VeloCity Bikes trademark. These counterfeit e-bikes pose serious safety risks...', true),
('LuxuryReplicas_HK (DHGate)', 'luxuryreplicas@dhgate.com', 'LuxeVault', 'counterfeit_product', 'draft', 'Dear LuxuryReplicas_HK, Your DHGate store sells replica products that infringe upon the LuxeVault registered trademark. We demand immediate removal of all listings...', true),
('AudioDeals_Store (Amazon)', 'audiodeals@amazon-seller.com', 'SoundWave Audio', 'counterfeit_product', 'sent', 'Dear AudioDeals_Store, Your counterfeit SoundWave Pro Headphones violate our trademark rights. We have documented evidence of 2,100+ counterfeit units sold...', true),
('Medicare-Plus-Discount.com Owner', 'admin@medicare-plus-discount.com', 'MediCare Plus', 'trademark_misuse', 'pending', 'Dear Site Owner, Your website medicare-plus-discount.com uses the MediCare Plus trademark without authorization to sell pharmaceutical products...', true),
('CrackZone Admin', 'abuse@crack-zone.to', 'PixelForge', 'software_piracy', 'sent', 'To the operators of CrackZone, Your distribution of cracked PixelForge software constitutes both copyright infringement and trademark violation...', true),
('GamerGear_CN (Wish Seller)', 'gamergear@wish.com', 'FrostByte Gaming', 'counterfeit_product', 'draft', 'Dear GamerGear_CN, Your Wish.com store sells counterfeit gaming controllers bearing the FrostByte Gaming trademark. These products do not meet our quality standards...', true),
('OrganicBargains (eBay)', 'organicbargains@ebay.com', 'GreenLeaf Organics', 'counterfeit_product', 'resolved', 'Dear OrganicBargains, Your eBay listings contain counterfeit GreenLeaf Organics products with fraudulent organic certifications...', true),
('@botanica_deals (Instagram)', 'botanica.deals@mail.com', 'Botanica Wellness', 'counterfeit_product', 'sent', 'Dear Account Holder, Your Instagram shop @botanica_deals sells counterfeit Botanica Wellness products that may pose health risks to consumers...', true),
('SneakerKing99 (StockX)', 'sneakerking99@stockx.com', 'PeakPerformance Athletics', 'counterfeit_product', 'pending', 'Dear SneakerKing99, You are selling counterfeit PeakPerformance running shoes on StockX. These inferior products damage our brand reputation...', true),
('APK_Mirror_Fake Admin', 'admin@fake-apk-site.com', 'MediCare Plus', 'software_piracy', 'sent', 'To the operator of the fraudulent APK distribution site, Your cloned MediCare Plus application constitutes trademark infringement and potentially violates HIPAA...', true),
('DroneFactory_SZ (Banggood)', 'dronefactory@banggood.com', 'AeroVista', 'counterfeit_product', 'draft', 'Dear DroneFactory_SZ, Your Banggood store sells counterfeit AeroVista drones that lack essential safety features and infringe our trademark...', true),
('SafetyGear_Direct (Amazon)', 'safetygear@amazon-seller.com', 'TerraFirm Construction', 'counterfeit_product', 'sent', 'Dear SafetyGear_Direct, Your counterfeit TerraFirm safety equipment fails to meet OSHA standards and infringes our registered trademark...', true),
('SolarPanel_Mfg (Alibaba)', 'solarpanel.mfg@alibaba.com', 'SolarFlare Energy', 'counterfeit_product', 'draft', 'Dear SolarPanel_Mfg, Your Alibaba listings for SolarFlare-branded solar panels constitute trademark infringement. The counterfeit panels present fire hazards...', true);

-- ===================== TRADEMARK SEARCHES =====================
INSERT INTO trademark_searches (search_term, jurisdiction, status, results_count, ai_analysis, searched_at) VALUES
('NovaTech', 'United States', 'completed', 3, 'Found 3 similar marks: NovaTech Solutions (Class 42, abandoned), NovaTeq (Class 9, active), NovaTech Industries (Class 9, active - your registration). Low conflict risk.', '2025-12-10 10:00:00'),
('AquaPure', 'United States', 'completed', 5, 'Found 5 similar marks: AquaPure (Class 32, active - yours), Aqua Pure (Class 11, active - water filters), AquaPure Plus (Class 5, pending). Moderate overlap in beverage space.', '2025-12-09 14:00:00'),
('SwiftLogix', 'European Union', 'completed', 2, 'Found 2 similar marks: SwiftLogix (Class 42, active - yours), Swift Logic (Class 9, active - different goods). Low conflict risk.', '2025-12-08 09:30:00'),
('GreenLeaf', 'United States', 'completed', 8, 'Found 8 similar marks across multiple classes. GreenLeaf is a common prefix. Recommend monitoring Class 29 and 30 competitors.', '2025-12-07 11:00:00'),
('VeloCity', 'United States', 'completed', 4, 'Found 4 similar marks: VeloCity (Class 12, active - yours), Velocity (multiple classes, active). Name similarity to common word "velocity" increases conflict potential.', '2025-12-06 15:30:00'),
('LuxeVault', 'United Kingdom', 'completed', 1, 'Found 1 match: LuxeVault (Class 14, active - your registration). Strong trademark with no similar marks in UK registry.', '2025-12-05 10:15:00'),
('MediCare Plus', 'United States', 'completed', 6, 'Found 6 similar marks. "Medicare" is a government program name - trademark scope may be limited. Recommend legal review.', '2025-12-04 13:45:00'),
('SoundWave', 'United States', 'completed', 7, 'Found 7 similar marks: SoundWave Audio (yours), Sound Wave (Class 9), SoundWave Music (Class 41), etc. Crowded space requires vigilant monitoring.', '2025-12-03 09:00:00'),
('PixelForge', 'European Union', 'completed', 2, 'Found 2 matches: PixelForge (Class 42, active - yours), Pixel Forge Labs (Class 9, pending). Monitor Pixel Forge Labs application.', '2025-12-02 16:00:00'),
('FrostByte', 'United States', 'completed', 3, 'Found 3 matches: FrostByte Gaming (yours), Frostbite (EA Games - different class), FrostByte Tech (Class 9, abandoned). Clear in gaming space.', '2025-12-01 11:30:00'),
('Botanica', 'Canada', 'completed', 9, 'Found 9 similar marks. "Botanica" is widely used in cosmetics. Strong competition for this term. Consider adding distinctive elements.', '2025-11-30 14:00:00'),
('CodeNexus', 'United States', 'completed', 2, 'Found 2 matches: CodeNexus (Class 42, yours), Code Nexus (Class 41, education - different goods). Low conflict risk.', '2025-11-29 10:30:00'),
('PeakPerformance', 'United States', 'completed', 5, 'Found 5 matches. Peak Performance is used by Swedish outdoor brand in EU. Potential conflict if expanding internationally. US registration is clear.', '2025-11-28 09:15:00'),
('SolarFlare', 'United States', 'pending', 4, 'Found 4 matches: SolarFlare Energy (yours, pending), Solar Flare (Class 11, active), SolarFlare Tech (Class 9, abandoned). Monitor Solar Flare in Class 11.', '2025-11-27 15:45:00'),
('TerraFirm', 'United States', 'completed', 3, 'Found 3 matches: TerraFirm Construction (yours), Terra Firma (Class 36, financial services), TerraFirma (Class 37, landscaping). Distinct enough in construction.', '2025-11-26 12:00:00');

-- ===================== SENTIMENT ANALYSES =====================
INSERT INTO sentiment_analyses (brand_name, source, period, positive_score, negative_score, neutral_score, summary, ai_analysis, analyzed_at) VALUES
('NovaTech', 'Twitter', 'Q4 2025', 72.50, 12.30, 15.20, 'Overwhelmingly positive sentiment driven by new AI features launch.', 'NovaTech brand sentiment is strong on Twitter. Key positive drivers: AI capabilities (mentioned 340 times), ease of use (280 times). Negative mentions primarily around pricing concerns. Recommend maintaining current messaging strategy.', '2025-12-10 10:00:00'),
('AquaPure', 'Instagram', 'Q4 2025', 68.00, 18.50, 13.50, 'Positive overall but counterfeit concerns affecting sentiment.', 'AquaPure enjoys strong brand loyalty on Instagram. Health-conscious consumers are primary advocates. However, counterfeit product reports are creating negative sentiment. Recommend public awareness campaign about authentic products.', '2025-12-09 10:00:00'),
('SwiftLogix', 'LinkedIn', 'Q4 2025', 81.20, 5.30, 13.50, 'Highly positive professional sentiment, strong B2B brand perception.', 'SwiftLogix has exceptional B2B sentiment on LinkedIn. Industry professionals praise reliability and integration capabilities. Very low negative sentiment. Enterprise clients are strong brand advocates.', '2025-12-08 10:00:00'),
('GreenLeaf Organics', 'Reddit', 'Q4 2025', 55.00, 30.20, 14.80, 'Mixed sentiment due to counterfeit concerns and pricing debates.', 'GreenLeaf faces divided sentiment on Reddit. Supporters praise quality and sustainability. Critics cite high pricing and counterfeit flooding reducing trust. Urgent need for authentication program.', '2025-12-07 10:00:00'),
('VeloCity Bikes', 'YouTube', 'Q4 2025', 76.30, 10.50, 13.20, 'Strong positive reviews from cycling community.', 'VeloCity Bikes receives excellent YouTube coverage. Top reviewers give 4.5+ star ratings. Minor complaints about weight and charging time. Counterfeit concerns mentioned in 15% of videos.', '2025-12-06 10:00:00'),
('LuxeVault', 'Instagram', 'Q4 2025', 85.40, 6.20, 8.40, 'Premium brand perception well maintained on luxury platform.', 'LuxeVault commands exceptional sentiment among luxury consumers on Instagram. Influencer partnerships driving 3x engagement. Phishing site reports are minimal but growing concern.', '2025-12-05 10:00:00'),
('MediCare Plus', 'Twitter', 'Q4 2025', 45.80, 38.50, 15.70, 'Troubled sentiment due to service outages and naming confusion.', 'MediCare Plus faces significant sentiment challenges. Service outage on Dec 4 caused spike in negative tweets. Brand confusion with Medicare government program persists. Recommend brand differentiation strategy.', '2025-12-04 10:00:00'),
('SoundWave Audio', 'Reddit', 'Q4 2025', 71.60, 15.80, 12.60, 'Strong audiophile community support despite counterfeit concerns.', 'SoundWave Audio enjoys loyal Reddit following. Audiophile community praises sound quality. Counterfeit flooding Amazon is primary concern. Community helping identify fakes organically.', '2025-12-03 10:00:00'),
('PixelForge', 'Twitter', 'Q4 2025', 52.30, 32.40, 15.30, 'Divided sentiment after buggy 4.0 release.', 'PixelForge 4.0 launch generated significant negative buzz. Autosave bug affected thousands of users. Pre-launch sentiment was 78% positive; post-launch dropped to 52%. Rapid patching recommended.', '2025-12-02 10:00:00'),
('FrostByte Gaming', 'Twitter', 'Q4 2025', 88.90, 4.50, 6.60, 'Exceptional sentiment driven by new game announcement.', 'FrostByte Gaming is experiencing peak brand sentiment. New RPG announcement drove record engagement. Community excitement is highest in company history. Maintain momentum with regular content drops.', '2025-12-01 10:00:00'),
('AeroVista', 'Instagram', 'Q4 2025', 74.20, 8.90, 16.90, 'Positive creative community engagement.', 'AeroVista drones are popular among creative professionals on Instagram. Stunning aerial photography driving organic reach. Minor concerns about drone regulations mentioned.', '2025-11-30 10:00:00'),
('Botanica Wellness', 'TikTok', 'Q4 2025', 82.70, 9.30, 8.00, 'Viral positive sentiment on TikTok beauty community.', 'Botanica Wellness is trending on TikTok beauty community. Multiple viral reviews. Counterfeit products are emerging concern but overall sentiment remains highly positive.', '2025-11-29 10:00:00'),
('CodeNexus', 'Twitter', 'Q4 2025', 79.40, 8.20, 12.40, 'Developer community excitement about collaboration features.', 'CodeNexus real-time collaboration launch generated strong positive sentiment among developers. Comparisons to GitHub are favorable. Minor concerns about pricing tiers.', '2025-11-28 10:00:00'),
('PeakPerformance Athletics', 'Reddit', 'Q4 2025', 60.50, 22.80, 16.70, 'Quality praised but pricing criticized.', 'PeakPerformance Athletics receives mixed Reddit sentiment. Running community praises durability and comfort. Price-conscious consumers find products overvalued. Counterfeit shoes on resale platforms cause trust issues.', '2025-11-27 10:00:00'),
('SolarFlare Energy', 'LinkedIn', 'Q4 2025', 90.10, 3.50, 6.40, 'Outstanding B2B sentiment after Series B funding.', 'SolarFlare Energy enjoys exceptional professional sentiment. Series B funding announcement drove record LinkedIn engagement. Industry leaders praising innovation. No significant negative sentiment detected.', '2025-11-25 10:00:00');

-- ===================== COMPETITORS =====================
INSERT INTO competitors (name, website, industry, threat_level, trademark_overlap, market_position, ai_analysis, last_analyzed) VALUES
('DataSphere Analytics', 'https://datasphere.io', 'Enterprise Software', 'high', 'NovaTech - competing in AI analytics space', 'Market leader', 'DataSphere is NovaTech primary competitor with 35% market share. Recent AI integration puts them ahead. Trademark "DataSphere" is distinct but they target same keywords. Monitor SEO overlap.', '2025-12-10 10:00:00'),
('PureSpring Water Co.', 'https://purespring.com', 'Beverages', 'medium', 'AquaPure - similar branding in purified water market', 'Growing challenger', 'PureSpring uses similar blue/white branding to AquaPure. Market overlap in premium water segment. No direct trademark conflict but visual branding similarity is concerning.', '2025-12-09 10:00:00'),
('LogiFlow Solutions', 'https://logiflow.com', 'Logistics Tech', 'medium', 'SwiftLogix - competing cloud logistics platform', 'Niche player', 'LogiFlow targets same mid-market logistics segment. Product features overlap significantly. Trademark is distinct. Monitor for feature-comparison marketing that could confuse customers.', '2025-12-08 10:00:00'),
('OrganicHarvest Foods', 'https://organicharvest.com', 'Organic Food', 'high', 'GreenLeaf Organics - direct competitor in organic snacks', 'Market leader', 'OrganicHarvest is the dominant organic food brand. Recently launched product line with green leaf imagery similar to GreenLeaf Organics. Potential trade dress concern.', '2025-12-07 10:00:00'),
('ThunderBolt E-Bikes', 'https://thunderbolt-bikes.com', 'Electric Vehicles', 'high', 'VeloCity Bikes - direct e-bike competitor', 'Growing fast', 'ThunderBolt is rapidly gaining market share with aggressive pricing. Their "Thunder" branding is distinct but they reference VeloCity in comparison ads. Monitor ad campaigns.', '2025-12-06 10:00:00'),
('PrestigeKeep', 'https://prestigekeep.com', 'Luxury Storage', 'low', 'LuxeVault - competing luxury storage brand', 'Smaller rival', 'PrestigeKeep competes in luxury storage niche. Different brand aesthetic and positioning. Minimal trademark overlap. Low threat to LuxeVault market position.', '2025-12-05 10:00:00'),
('HealthBridge Digital', 'https://healthbridge.io', 'Digital Health', 'high', 'MediCare Plus - competing telemedicine platform', 'Established player', 'HealthBridge is a well-funded competitor in telemedicine. No trademark overlap. However, they are running negative comparison campaigns. Monitor for disparagement.', '2025-12-04 10:00:00'),
('BassLine Audio', 'https://basslineaudio.com', 'Consumer Electronics', 'medium', 'SoundWave Audio - competing premium headphone brand', 'Growing brand', 'BassLine Audio targets same audiophile market. Product quality is comparable. No trademark conflict. They are gaining TikTok influence. Monitor social media positioning.', '2025-12-03 10:00:00'),
('CanvasFlow Studio', 'https://canvasflow.com', 'Design Software', 'high', 'PixelForge - direct competitor in design tools', 'Rapid growth', 'CanvasFlow has capitalized on PixelForge 4.0 bugs by offering free migration tools. Aggressive competitive strategy. Trademark is distinct. Monitor for unfair trade practices.', '2025-12-02 10:00:00'),
('IceStorm Games', 'https://icestorm-games.com', 'Gaming', 'medium', 'FrostByte Gaming - competing game studio', 'Indie studio', 'IceStorm Games operates in same RPG genre. "Ice" theme similar to "Frost" theme. Brand confusion possible among casual gamers. Monitor game title similarities.', '2025-12-01 10:00:00'),
('SkyEye Technologies', 'https://skyeye-tech.com', 'Drone Tech', 'medium', 'AeroVista - competing drone manufacturer', 'Niche competitor', 'SkyEye targets commercial drone market similar to AeroVista. Different brand positioning. May compete for same government contracts. Monitor patent landscape.', '2025-11-30 10:00:00'),
('NaturaSkin Organics', 'https://naturaskin.com', 'Cosmetics', 'high', 'Botanica Wellness - direct skincare competitor', 'Market leader', 'NaturaSkin is the leading natural skincare brand. Their new "Botanical" product line creates naming confusion with Botanica Wellness. Potential trademark dilution concern.', '2025-11-29 10:00:00'),
('DevHub Platform', 'https://devhub.io', 'Developer Tools', 'medium', 'CodeNexus - competing developer collaboration tool', 'Established', 'DevHub has larger user base but CodeNexus is gaining ground with real-time features. No trademark overlap. Monitor for competitive messaging.', '2025-11-28 10:00:00'),
('ApexFit Apparel', 'https://apexfit.com', 'Athletic Wear', 'high', 'PeakPerformance Athletics - direct competitor in sportswear', 'Growing fast', 'ApexFit uses similar mountain/peak imagery to PeakPerformance. "Apex" and "Peak" convey similar meaning. Potential trade dress and descriptive term overlap. Legal review recommended.', '2025-11-27 10:00:00'),
('GreenPower Solar', 'https://greenpower-solar.com', 'Renewable Energy', 'medium', 'SolarFlare Energy - competing solar company', 'Regional player', 'GreenPower operates in same renewable energy space. No trademark similarity. May compete for same utility contracts. Monitor expansion plans.', '2025-11-25 10:00:00');

-- ===================== LOGO ANALYSES =====================
INSERT INTO logo_analyses (original_brand, compared_brand, similarity_score, visual_elements, color_similarity, shape_similarity, risk_level, ai_analysis, analyzed_at) VALUES
('NovaTech', 'NovaTeq', 72.50, 'Both use star/nova burst icon, similar sans-serif font', 65.00, 80.00, 'high', 'Significant visual overlap. Both brands use a burst/nova motif. NovaTech uses blue (#1E40AF), NovaTeq uses teal (#0D9488). Font style is similar. Risk of consumer confusion in digital contexts.', '2025-12-10 10:00:00'),
('AquaPure', 'PureSpring Water', 45.30, 'Both use water droplet imagery, blue color schemes', 78.00, 30.00, 'medium', 'Color schemes are similar (both use blue). AquaPure uses a droplet icon while PureSpring uses wave imagery. Shape similarity is low but color overlap could cause shelf confusion.', '2025-12-09 10:00:00'),
('GreenLeaf Organics', 'OrganicHarvest', 62.80, 'Both use leaf motifs, green color palette, organic text styling', 85.00, 55.00, 'high', 'High color similarity with both using natural green tones. GreenLeaf uses a single leaf icon; OrganicHarvest new line uses double leaf design. Combined with "organic" descriptor, confusion risk is elevated.', '2025-12-07 10:00:00'),
('VeloCity Bikes', 'ThunderBolt E-Bikes', 28.50, 'Different motifs - bicycle vs lightning bolt, contrasting colors', 20.00, 15.00, 'low', 'Logos are visually distinct. VeloCity uses orange/warm tones with bicycle silhouette. ThunderBolt uses yellow/black with lightning motif. No meaningful visual confusion risk.', '2025-12-06 10:00:00'),
('LuxeVault', 'PrestigeKeep', 38.20, 'Both use lock/vault imagery but different execution styles', 45.00, 35.00, 'low', 'Both logos reference security/storage concepts. LuxeVault uses gold/black with minimalist vault door. PrestigeKeep uses silver/blue with ornate key design. Sufficiently distinct.', '2025-12-05 10:00:00'),
('SoundWave Audio', 'BassLine Audio', 55.40, 'Both use sound wave visualization, similar typographic weight', 40.00, 70.00, 'medium', 'Shape similarity is notable as both incorporate sound wave graphics. Color palettes differ significantly. The wave pattern execution is similar enough to warrant monitoring.', '2025-12-03 10:00:00'),
('PixelForge', 'CanvasFlow Studio', 32.10, 'Different concepts - pixel grid vs flowing canvas, distinct colors', 25.00, 20.00, 'low', 'Logos are visually distinct. PixelForge uses pixelated anvil icon in purple. CanvasFlow uses flowing gradient in orange/pink. No consumer confusion risk.', '2025-12-02 10:00:00'),
('FrostByte Gaming', 'IceStorm Games', 58.70, 'Both use ice/frost crystal imagery, cool blue palettes', 82.00, 48.00, 'medium', 'High color similarity with both using icy blue palettes. FrostByte uses hexagonal crystal; IceStorm uses storm cloud with ice. Genre theming creates visual category overlap.', '2025-12-01 10:00:00'),
('Botanica Wellness', 'NaturaSkin Organics', 67.40, 'Both use botanical leaf designs, earth tone palettes', 75.00, 62.00, 'high', 'Significant overlap in botanical visual language. Both use hand-drawn leaf illustrations with earth tones. Botanica is green-focused while NaturaSkin uses more brown/gold. High confusion risk in retail.', '2025-11-29 10:00:00'),
('PeakPerformance Athletics', 'ApexFit Apparel', 71.20, 'Both use mountain/peak silhouettes, athletic typography', 60.00, 78.00, 'high', 'Mountain peak iconography is nearly identical in concept. Both use angular, dynamic typography. PeakPerformance uses red/black while ApexFit uses blue/white. Shape similarity is high risk.', '2025-11-27 10:00:00'),
('CodeNexus', 'DevHub Platform', 25.60, 'Completely different visual approaches - code brackets vs hub icon', 30.00, 15.00, 'low', 'No meaningful visual overlap. CodeNexus uses code bracket iconography in dark purple. DevHub uses circular hub design in green. Zero consumer confusion risk.', '2025-11-28 10:00:00'),
('SolarFlare Energy', 'GreenPower Solar', 42.30, 'Both use sun imagery but different execution', 50.00, 38.00, 'low', 'Both incorporate solar/sun motifs as expected in solar industry. SolarFlare uses stylized sun flare in orange. GreenPower uses green sun with leaf. Distinct enough in execution.', '2025-11-25 10:00:00'),
('MediCare Plus', 'HealthBridge Digital', 35.80, 'Medical cross vs bridge icon, different color approaches', 42.00, 22.00, 'low', 'MediCare Plus uses medical cross with blue gradient. HealthBridge uses bridge icon in teal. Visual distinction is clear despite same industry.', '2025-12-04 10:00:00'),
('AeroVista', 'SkyEye Technologies', 52.90, 'Both use aerial/eye imagery, sky blue palettes', 72.00, 40.00, 'medium', 'Both brands use sky/aerial concepts with blue palettes. AeroVista uses drone silhouette. SkyEye uses stylized eye with drone wing. Color overlap is notable. Monitor for confusion.', '2025-11-30 10:00:00'),
('TerraFirm Construction', 'BuildStrong Corp', 30.50, 'Different motifs - earth/terrain vs stronghold design', 35.00, 28.00, 'low', 'Logos are visually distinct. TerraFirm uses earth/ground cross-section in brown/green. BuildStrong uses shield design in grey/red. No meaningful confusion risk.', '2025-11-26 10:00:00');

-- ===================== MARKETPLACE LISTINGS =====================
INSERT INTO marketplace_listings (marketplace, product_title, seller, price, url, status, is_counterfeit, trademark_matched, detected_at) VALUES
('Amazon', 'NovaTech Enterprise Analytics Pro License', 'TechDeals_Express', 999.99, 'https://amazon.com/dp/B09ML001', 'active', true, 'NovaTech', '2025-12-10 08:00:00'),
('Amazon', 'AquaPure Premium Water 24-Pack', 'BestWaterDeals', 8.99, 'https://amazon.com/dp/B09ML002', 'active', true, 'AquaPure', '2025-12-09 09:00:00'),
('eBay', 'GreenLeaf Organic Energy Bars 12-Pack', 'OrganicBargains', 15.99, 'https://ebay.com/itm/345678901', 'removed', true, 'GreenLeaf Organics', '2025-12-08 10:00:00'),
('AliExpress', 'VeloCity Electric Mountain Bike 750W', 'ShenZhen_eBikes', 299.00, 'https://aliexpress.com/item/1234567', 'active', true, 'VeloCity Bikes', '2025-12-07 11:00:00'),
('DHGate', 'LuxeVault Premium Jewelry Storage Box', 'LuxuryReplicas_HK', 45.00, 'https://dhgate.com/product/8901234', 'active', true, 'LuxeVault', '2025-12-06 12:00:00'),
('Amazon', 'SoundWave Pro Noise Cancelling Headphones', 'AudioDeals_Store', 39.99, 'https://amazon.com/dp/B09ML003', 'active', true, 'SoundWave Audio', '2025-12-05 13:00:00'),
('Wish', 'FrostByte Pro Gaming Controller Wireless', 'GamerGear_CN', 12.99, 'https://wish.com/product/5678901', 'active', true, 'FrostByte Gaming', '2025-12-04 14:00:00'),
('Amazon', 'Botanica Wellness Anti-Aging Face Serum', 'BeautyDeals_2024', 19.99, 'https://amazon.com/dp/B09ML004', 'investigating', true, 'Botanica Wellness', '2025-12-03 15:00:00'),
('StockX', 'PeakPerformance Ultra Running Shoes', 'SneakerKing99', 89.99, 'https://stockx.com/peakperformance-ultra', 'active', true, 'PeakPerformance Athletics', '2025-12-02 16:00:00'),
('Alibaba', 'SolarFlare 400W Monocrystalline Panels', 'SolarPanel_Mfg', 199.00, 'https://alibaba.com/product/7890123', 'active', true, 'SolarFlare Energy', '2025-12-01 17:00:00'),
('Amazon', 'AeroVista Drone 4K Camera GPS', 'DroneDeals_Store', 149.99, 'https://amazon.com/dp/B09ML005', 'active', true, 'AeroVista', '2025-11-30 18:00:00'),
('Banggood', 'TerraFirm Professional Hard Hat OSHA', 'SafetyGear_Direct', 12.99, 'https://banggood.com/product/2345678', 'investigating', true, 'TerraFirm Construction', '2025-11-29 19:00:00'),
('Amazon', 'NovaTech Data Analytics Starter Pack', 'CloudSoftware_Hub', 199.99, 'https://amazon.com/dp/B09ML006', 'active', false, 'NovaTech', '2025-11-28 08:30:00'),
('eBay', 'PixelForge Creative Suite 4.0 License Key', 'SoftwareKeys_Pro', 49.99, 'https://ebay.com/itm/456789012', 'active', true, 'PixelForge', '2025-11-27 09:30:00'),
('Amazon', 'MediCare Plus Telehealth Kit', 'HealthTech_Direct', 79.99, 'https://amazon.com/dp/B09ML007', 'active', false, 'MediCare Plus', '2025-11-26 10:30:00'),
('AliExpress', 'CodeNexus Pro Developer Toolkit', 'DevTools_Factory', 29.99, 'https://aliexpress.com/item/3456789', 'active', true, 'CodeNexus', '2025-11-25 11:30:00');

-- ===================== LEGAL CASES =====================
INSERT INTO legal_cases (case_number, title, defendant, case_type, status, jurisdiction, filing_date, description, outcome, damages) VALUES
('TM-2025-001', 'NovaTech v. NovaTeq Solutions', 'NovaTeq Solutions LLC', 'trademark_infringement', 'open', 'U.S. District Court, Northern District of California', '2025-06-15', 'Trademark infringement claim for confusingly similar mark in Class 9 software products.', NULL, NULL),
('TM-2025-002', 'AquaPure v. BestWaterDeals', 'BestWaterDeals Inc.', 'counterfeit_goods', 'open', 'U.S. District Court, Southern District of New York', '2025-08-22', 'Counterfeit AquaPure water products sold on Amazon marketplace.', NULL, NULL),
('TM-2025-003', 'VeloCity v. ShenZhen eBikes Co.', 'ShenZhen eBikes Co. Ltd.', 'counterfeit_goods', 'open', 'International Trade Commission', '2025-09-10', 'Import ban request for counterfeit VeloCity electric bicycles from China.', NULL, NULL),
('TM-2025-004', 'LuxeVault v. Unknown (UDRP)', 'John Doe (luxevaultt.com)', 'domain_dispute', 'pending', 'WIPO Arbitration and Mediation Center', '2025-10-01', 'UDRP complaint for typosquatting domain used for phishing.', NULL, NULL),
('TM-2025-005', 'GreenLeaf v. OrganicBargains', 'OrganicBargains LLC', 'counterfeit_goods', 'settled', 'U.S. District Court, District of Oregon', '2025-04-18', 'Settlement reached for counterfeit organic food products sold on eBay.', 'Settled. Defendant agreed to cease sales and pay damages.', 125000.00),
('TM-2025-006', 'SoundWave v. AudioDeals Store', 'AudioDeals Store Ltd.', 'counterfeit_goods', 'open', 'U.S. District Court, Western District of Washington', '2025-11-05', 'Counterfeit headphones sold on Amazon causing consumer safety concerns.', NULL, NULL),
('TM-2025-007', 'PixelForge v. CrackZone', 'CrackZone Operators (Unknown)', 'software_piracy', 'open', 'U.S. District Court, Northern District of California', '2025-07-20', 'Criminal referral for software piracy and malware distribution.', NULL, NULL),
('TM-2024-008', 'MediCare Plus v. Medicare-Plus-Discount.com', 'MedDiscount LLC', 'trademark_misuse', 'resolved', 'U.S. District Court, Eastern District of Virginia', '2024-12-10', 'Unauthorized use of MediCare Plus brand for pharmacy services.', 'Injunction granted. Domain ordered transferred.', 75000.00),
('TM-2025-009', 'Botanica v. NaturaSkin (Trade Dress)', 'NaturaSkin Organics Inc.', 'trade_dress', 'open', 'U.S. District Court, Central District of California', '2025-10-15', 'Trade dress infringement claim for similar botanical leaf packaging design.', NULL, NULL),
('TM-2025-010', 'PeakPerformance v. ApexFit', 'ApexFit Apparel Corp.', 'trademark_infringement', 'open', 'U.S. District Court, District of Colorado', '2025-08-30', 'Trademark infringement for mountain peak logo similarity in athletic apparel.', NULL, NULL),
('TM-2024-011', 'FrostByte v. FrostBite (Opposition)', 'Electronic Arts Inc.', 'trademark_opposition', 'resolved', 'Trademark Trial and Appeal Board', '2024-06-01', 'Opposition proceeding resolved. Marks found sufficiently distinct in different classes.', 'Opposition dismissed. Both marks may coexist.', 0.00),
('TM-2025-012', 'CodeNexus v. Credential Harvesters', 'Unknown (codenexus-pro.com)', 'cybercrime', 'open', 'U.S. District Court, District of Delaware', '2025-11-20', 'Criminal complaint for phishing operation targeting CodeNexus users.', NULL, NULL),
('TM-2024-013', 'TerraFirm v. TerraFirma Landscaping', 'TerraFirma Landscaping LLC', 'trademark_infringement', 'settled', 'U.S. District Court, District of Texas', '2024-09-15', 'Coexistence agreement reached for similar marks in different construction sub-sectors.', 'Settled with coexistence agreement. Geographic and service limitations agreed.', 0.00),
('TM-2025-014', 'AeroVista v. DroneFactory_SZ', 'DroneFactory SZ Co. Ltd.', 'counterfeit_goods', 'open', 'International Trade Commission', '2025-11-01', 'Import ban request for counterfeit AeroVista drones with safety defects.', NULL, NULL),
('TM-2025-015', 'SolarFlare v. SolarPanel_Mfg', 'SolarPanel Manufacturing Co.', 'counterfeit_goods', 'open', 'U.S. District Court, District of Arizona', '2025-12-01', 'Counterfeit solar panels posing fire hazard sold under SolarFlare brand.', NULL, NULL);

-- ===================== REPORTS =====================
INSERT INTO reports (title, report_type, period, status, content, ai_generated, generated_at) VALUES
('Q4 2025 Brand Protection Summary', 'quarterly_summary', 'Q4 2025', 'published', 'Executive Summary: 47 new infringement cases detected. 12 cease & desist letters sent. 3 legal proceedings initiated. Overall brand health score: 7.2/10.', true, '2025-12-10 10:00:00'),
('NovaTech Trademark Portfolio Review', 'portfolio_review', '2025', 'published', 'NovaTech trademark portfolio consists of 1 active registration. Renewal due 2032. No opposition proceedings pending. Recommend filing in additional classes.', true, '2025-12-09 10:00:00'),
('Counterfeit Activity Report - December 2025', 'counterfeit_report', 'Dec 2025', 'published', 'Detected 15 counterfeit product listings across 8 marketplaces. Total estimated revenue loss: $2.3M. Priority takedown actions initiated for 5 critical listings.', true, '2025-12-08 10:00:00'),
('Domain Monitoring Report - Q4 2025', 'domain_report', 'Q4 2025', 'published', 'Monitored 16 suspicious domains. 4 classified as critical threats. 2 UDRP proceedings initiated. 6 domains marked for ongoing surveillance.', true, '2025-12-07 10:00:00'),
('Social Media Brand Sentiment Analysis', 'sentiment_report', 'Q4 2025', 'draft', 'Cross-platform sentiment analysis for 16 monitored brands. Average positive sentiment: 69.2%. Key concerns: counterfeit awareness, service reliability.', true, '2025-12-06 10:00:00'),
('Legal Proceedings Status Update', 'legal_report', 'Dec 2025', 'published', '15 active legal proceedings. 3 settlements reached totaling $200K in damages. 5 new filings in Q4. International enforcement actions pending in 2 jurisdictions.', true, '2025-12-05 10:00:00'),
('Marketplace Counterfeit Detection Report', 'marketplace_report', 'Nov 2025', 'published', 'Scanned 6 major marketplaces. Identified 16 counterfeit listings. Amazon remains primary counterfeit channel (40%). Takedown success rate: 67%.', true, '2025-12-04 10:00:00'),
('Competitor Brand Analysis - Q4 2025', 'competitor_report', 'Q4 2025', 'draft', 'Analyzed 15 key competitors across 10 industries. 4 brands identified with high trademark overlap risk. 2 potential trade dress claims recommended.', true, '2025-12-03 10:00:00'),
('Logo Similarity Audit Report', 'logo_report', '2025', 'published', 'Conducted 15 logo comparisons. 3 high-risk similarities identified. Recommended legal action for NovaTech vs NovaTeq and PeakPerformance vs ApexFit cases.', true, '2025-12-02 10:00:00'),
('Annual Brand Protection Strategy 2026', 'strategy_report', '2026', 'draft', 'Recommended 2026 strategy: Expand monitoring to 3 additional marketplaces, implement AI-powered real-time detection, increase legal budget by 25%.', true, '2025-12-01 10:00:00'),
('Cease & Desist Effectiveness Report', 'effectiveness_report', 'Q4 2025', 'published', '15 C&D letters issued in Q4. Response rate: 60%. Successful takedowns: 45%. Average response time: 12 days. Recommend escalation timeline reduction.', true, '2025-11-30 10:00:00'),
('International Trademark Filing Recommendations', 'filing_report', '2025', 'draft', 'Based on market analysis, recommend filing in EU, UK, Canada, Australia, and Japan for top 5 brands. Estimated filing costs: $45,000.', true, '2025-11-29 10:00:00'),
('AI Detection System Performance Report', 'system_report', 'Q4 2025', 'published', 'AI detection system processed 50,000 potential infringements. True positive rate: 89%. False positive rate: 7%. Average detection time: 2.3 hours.', true, '2025-11-28 10:00:00'),
('Risk Assessment Report - Critical Brands', 'risk_report', 'Dec 2025', 'published', 'Risk assessment for top 5 at-risk brands: MediCare Plus (high), GreenLeaf Organics (high), SoundWave Audio (medium), PeakPerformance (medium), NovaTech (medium).', true, '2025-11-27 10:00:00'),
('Monthly Executive Dashboard - November 2025', 'executive_dashboard', 'Nov 2025', 'published', 'November highlights: 12 new infringements detected, 4 legal wins, $125K in damages recovered, brand health improved by 3% MoM.', true, '2025-11-26 10:00:00');

-- ===================== ALERTS =====================
INSERT INTO alerts (title, alert_type, severity, source, message, is_read, related_id, related_type, triggered_at) VALUES
('Critical Phishing Site Detected', 'domain_threat', 'critical', 'domain_monitor', 'Phishing site luxevaultt.com detected mimicking LuxeVault storefront. Immediate action required.', false, 4, 'domains', '2025-12-10 08:00:00'),
('New Counterfeit Listing on Amazon', 'counterfeit_alert', 'high', 'marketplace_scan', 'Counterfeit SoundWave headphones detected on Amazon. Seller: AudioDeals_Store. 2,100+ units sold.', false, 5, 'counterfeits', '2025-12-09 09:15:00'),
('Trademark Opposition Filing', 'legal_alert', 'high', 'legal_monitor', 'New trademark application filed for "NovaTeq Solutions" in Class 9. Potential conflict with NovaTech registration.', true, 1, 'legal_cases', '2025-12-08 10:30:00'),
('Social Media Impersonation', 'social_threat', 'medium', 'social_monitor', 'TikTok account @fakesoundwave promoting counterfeit products. 45K followers reached.', false, 8, 'infringements', '2025-12-07 11:00:00'),
('Counterfeit Safety Hazard', 'safety_alert', 'critical', 'counterfeit_detect', 'Counterfeit VeloCity e-bikes with unsafe batteries detected. Fire hazard risk. 156 units shipped.', false, 3, 'counterfeits', '2025-12-06 12:00:00'),
('Domain Registration Alert', 'domain_threat', 'medium', 'domain_monitor', 'New domain solarflare-panels.com registered. 86.7% similarity to SolarFlare Energy trademark.', false, 16, 'domains', '2025-12-05 13:00:00'),
('Negative Sentiment Spike', 'sentiment_alert', 'medium', 'sentiment_monitor', 'PixelForge experiencing 20% drop in positive sentiment following 4.0 release bugs.', true, 9, 'sentiment_analyses', '2025-12-04 14:00:00'),
('Cease & Desist Response Received', 'legal_alert', 'low', 'legal_monitor', 'OrganicBargains (eBay) has agreed to cease sales of counterfeit GreenLeaf products.', true, 9, 'cease_desist_letters', '2025-12-03 15:00:00'),
('Malware Distribution Alert', 'security_alert', 'critical', 'security_monitor', 'Cracked PixelForge software with embedded keylogger detected. 8,500+ installations estimated.', false, 6, 'counterfeits', '2025-12-02 16:00:00'),
('International Counterfeit Ring', 'counterfeit_alert', 'critical', 'intelligence', 'Coordinated counterfeit operation detected across AliExpress, DHGate, and Wish targeting multiple brands.', false, NULL, 'counterfeits', '2025-12-01 17:00:00'),
('Trademark Renewal Reminder', 'renewal_alert', 'low', 'portfolio_manager', 'GreenLeaf Organics trademark expiring in 2030. Recommend initiating renewal process by 2029.', true, 4, 'trademarks', '2025-11-30 08:00:00'),
('Competitor Brand Strategy Change', 'competitor_alert', 'medium', 'competitor_monitor', 'CanvasFlow Studio launching free migration tool targeting PixelForge users. Aggressive competitive strategy.', false, 9, 'competitors', '2025-11-29 09:00:00'),
('UDRP Proceeding Update', 'legal_alert', 'high', 'legal_monitor', 'WIPO panel assigned for LuxeVault vs luxevaultt.com domain dispute. Hearing scheduled.', false, 4, 'legal_cases', '2025-11-28 10:00:00'),
('New Counterfeit Medical Device', 'safety_alert', 'critical', 'counterfeit_detect', 'Cloned MediCare Plus app collecting patient medical data. HIPAA violation. 3,200+ installs.', false, 12, 'counterfeits', '2025-11-27 11:00:00'),
('Monthly Protection Score Update', 'system_alert', 'low', 'system', 'November 2025 brand protection score: 7.2/10. Improved from 6.8 in October. 5 resolved cases contributed to improvement.', true, NULL, 'reports', '2025-11-26 12:00:00'),
('Trade Dress Concern Identified', 'legal_alert', 'high', 'ai_analysis', 'NaturaSkin new Botanical product line shows concerning similarity to Botanica Wellness trade dress. Legal review recommended.', false, 12, 'competitors', '2025-11-25 13:00:00');

-- ===================== AUDIT LOGS =====================
INSERT INTO audit_logs (user_email, action, entity_type, entity_id, details, ip_address, performed_at) VALUES
('demo@trademark.com', 'login', 'user', 1, 'Successful login from Chrome/Windows', '192.168.1.100', '2025-12-10 08:00:00'),
('sarah.chen@trademark.com', 'create', 'infringement', 15, 'New infringement report created for PeakPerformance outlet site', '192.168.1.101', '2025-12-10 09:30:00'),
('demo@trademark.com', 'generate', 'cease_desist', 14, 'AI-generated cease & desist letter for SafetyGear_Direct', '192.168.1.100', '2025-12-10 10:15:00'),
('james.wilson@trademark.com', 'update', 'infringement', 4, 'Updated infringement status from pending to resolved', '192.168.1.102', '2025-12-09 11:00:00'),
('maria.garcia@trademark.com', 'search', 'trademark_search', 1, 'Trademark search for NovaTech in US jurisdiction', '192.168.1.103', '2025-12-09 14:30:00'),
('david.kim@trademark.com', 'analyze', 'sentiment', 1, 'AI sentiment analysis for NovaTech on Twitter Q4 2025', '192.168.1.104', '2025-12-08 09:00:00'),
('emma.thompson@trademark.com', 'create', 'legal_case', 15, 'New legal case filed: SolarFlare v. SolarPanel_Mfg', '192.168.1.105', '2025-12-08 13:45:00'),
('demo@trademark.com', 'generate', 'report', 1, 'AI-generated Q4 2025 Brand Protection Summary', '192.168.1.100', '2025-12-07 16:00:00'),
('sarah.chen@trademark.com', 'update', 'domain', 4, 'Updated domain luxevaultt.com threat level to critical', '192.168.1.101', '2025-12-07 10:30:00'),
('robert.jones@trademark.com', 'delete', 'marketplace_listing', 3, 'Removed eBay listing after successful takedown', '192.168.1.106', '2025-12-06 15:00:00'),
('lisa.wang@trademark.com', 'analyze', 'logo', 10, 'AI logo analysis: PeakPerformance vs ApexFit', '192.168.1.107', '2025-12-06 11:30:00'),
('michael.brown@trademark.com', 'create', 'alert', 10, 'Created alert for international counterfeit ring', '192.168.1.108', '2025-12-05 17:00:00'),
('jennifer.lee@trademark.com', 'analyze', 'competitor', 9, 'AI competitor analysis for CanvasFlow Studio', '192.168.1.109', '2025-12-05 09:15:00'),
('demo@trademark.com', 'update', 'cease_desist', 5, 'Updated C&D status to sent for AudioDeals_Store', '192.168.1.100', '2025-12-04 14:00:00'),
('alex.martinez@trademark.com', 'view', 'report', 6, 'Viewed Legal Proceedings Status Update report', '192.168.1.110', '2025-12-04 10:45:00'),
('kevin.patel@trademark.com', 'analyze', 'domain', 13, 'AI domain analysis for codenexus-pro.com phishing site', '192.168.1.111', '2025-12-03 08:30:00');
